#
# TABLE STRUCTURE FOR: media
#

DROP TABLE IF EXISTS `media`;

CREATE TABLE `media` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `media_type_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `filename` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `size` int(11) DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  UNIQUE KEY `id` (`id`),
  KEY `user_id` (`user_id`),
  KEY `media_type_id` (`media_type_id`),
  CONSTRAINT `media_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `media_ibfk_2` FOREIGN KEY (`media_type_id`) REFERENCES `media_types` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('1', '1', '178', 'Molestiae consectetur perferendis eum voluptas quibusdam eaque. Vel reprehenderit sequi hic pariatur. Enim possimus architecto quia non deleniti.', 'voluptas', 617827, NULL, '1975-09-14 11:50:56', '1994-04-27 03:50:06');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('2', '2', '179', 'Repellendus et sapiente et et officia earum molestiae exercitationem. Et vero dolores cumque provident et eos ullam. Mollitia nemo fugit soluta similique.', 'quasi', 38, NULL, '1982-10-17 11:04:44', '1997-02-28 21:14:54');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('3', '3', '180', 'Et at iure distinctio ullam magni ut omnis. Expedita cupiditate quaerat sit est earum odit soluta nesciunt. Quia occaecati non iste culpa. Eos ullam magnam ratione veritatis vel quas.', 'dignissimos', 69778, NULL, '2006-04-08 21:25:06', '1994-10-19 12:57:52');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('4', '4', '181', 'Et ipsam vitae qui eos ut animi. Aspernatur mollitia omnis rerum. Provident cum facere accusantium ut. Qui atque voluptate voluptatibus dolore quaerat.', 'eaque', 1, NULL, '1981-11-04 00:25:53', '1972-12-29 16:54:02');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('5', '5', '182', 'Est in voluptas hic. A omnis laborum consequatur eos ut eius. Fugiat harum doloremque necessitatibus nostrum. Debitis unde laboriosam sint est. Et earum blanditiis praesentium nam quod hic.', 'quia', 28717684, NULL, '1980-09-22 15:50:32', '2012-03-02 05:18:14');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('6', '6', '183', 'Velit quisquam cumque aut labore quis. Sit atque beatae repudiandae non eius provident quo. Et et maxime a laudantium repellendus et consequuntur.', 'aut', 9, NULL, '1992-10-02 09:22:55', '1977-08-18 09:59:03');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('7', '7', '185', 'Est itaque molestias quae quo eum voluptatem provident. Doloremque vel suscipit et et. Est esse voluptatem rerum temporibus accusamus velit nostrum.', 'deleniti', 7417308, NULL, '1986-03-08 00:02:38', '1993-03-17 22:20:22');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('8', '8', '187', 'Ducimus beatae dolorum soluta sit. Ea non voluptatem sit reprehenderit laborum. Occaecati error dolor sit rerum aut ratione. Qui rem expedita deleniti necessitatibus nostrum.', 'temporibus', 7653046, NULL, '2002-09-04 03:54:30', '2011-12-29 07:28:39');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('9', '9', '188', 'Sit saepe quasi impedit explicabo enim dolor. Possimus sunt sapiente qui eos sed distinctio. Eius explicabo cum similique facere dolorem facilis.', 'inventore', 2, NULL, '1978-10-29 06:25:38', '2005-04-01 23:12:44');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('10', '10', '189', 'Earum aperiam est error exercitationem dignissimos aliquid omnis. Est dolorem non quis. Necessitatibus odit consequuntur aliquid et voluptates.', 'culpa', 157, NULL, '1984-11-28 04:28:11', '2013-11-16 09:49:42');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('11', '1', '192', 'Illo molestias aut possimus qui omnis. Aut est a pariatur eveniet qui veniam. Dolor dolore optio illum omnis qui ratione ratione ea. Perspiciatis enim sit velit laborum velit laborum. Est repellat nisi voluptatem aut hic provident necessitatibus.', 'nisi', 534, NULL, '1988-07-18 22:31:21', '1970-02-13 04:00:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('12', '2', '196', 'Quam repellat numquam ducimus ratione non quos. Magnam similique exercitationem nobis ducimus reiciendis. Asperiores vel adipisci nobis consequuntur nemo. Quam ea labore ullam consequatur sunt.', 'iusto', 74, NULL, '1999-11-22 17:14:03', '1996-09-03 00:41:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('13', '3', '197', 'Qui est vel sunt suscipit voluptatibus. Corrupti dolor sint non quia molestias. Impedit eveniet repudiandae recusandae dolorem quae dignissimos possimus. Ea enim sunt vero fuga.', 'minima', 80594, NULL, '2021-03-19 14:20:45', '1982-12-28 03:20:23');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('14', '4', '198', 'Aut sed rerum occaecati libero molestiae magni. A non nihil pariatur aliquid aliquid commodi magnam. Nobis laborum consequatur occaecati.', 'ut', 0, NULL, '2002-01-11 21:19:07', '1999-02-02 17:04:08');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('15', '5', '199', 'Deserunt sint dolor qui officia quia voluptatum non asperiores. Vero ducimus rerum amet quae qui laborum. Officia fugit maiores qui veritatis sint in. Atque mollitia similique fugit sequi ea reiciendis deserunt. Odio dolores dicta aliquid fugit suscipit fuga quidem.', 'sequi', 200818717, NULL, '2009-01-12 22:20:21', '1999-03-02 21:59:17');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('16', '6', '201', 'Voluptatum et enim minima tempore. Provident nostrum velit harum voluptas. Nesciunt ullam aut sint id modi sit. Et nostrum non quae. Tenetur quia et qui et.', 'voluptas', 5850, NULL, '1979-11-20 13:44:11', '1972-05-30 00:02:57');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('17', '7', '202', 'Ut sit voluptatibus laborum nihil ipsum. Accusamus molestiae ratione libero et. Culpa dignissimos culpa iure asperiores occaecati recusandae omnis. Rerum sint minima consequatur itaque.', 'itaque', 33558895, NULL, '1986-12-23 17:19:49', '1996-12-17 23:05:25');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('18', '8', '204', 'Assumenda placeat cupiditate sint repudiandae quia ut quam. Fuga quae vero dolor est cum quae. Cupiditate voluptate nam saepe natus. Similique non voluptatem nesciunt dignissimos.', 'quos', 5756, NULL, '2015-04-04 12:18:10', '2010-05-27 23:18:36');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('19', '9', '207', 'Ratione consequuntur molestiae suscipit voluptas consectetur fugiat aut dolorum. Perspiciatis excepturi iste facilis iusto necessitatibus vero voluptatem. Sit sed minima ducimus nemo explicabo. Exercitationem non quasi dolores sit.', 'asperiores', 58883, NULL, '1975-07-04 04:48:17', '1994-10-25 19:07:09');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('20', '10', '209', 'Veritatis impedit perferendis fuga quas alias autem. Exercitationem facere est distinctio ut adipisci provident. Consectetur natus ut qui cupiditate. Dolorum architecto alias alias aut deserunt harum enim.', 'optio', 5480, NULL, '1974-07-26 18:01:45', '2015-12-07 14:00:12');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('21', '1', '210', 'Magnam aut cum distinctio ab inventore quia. Quod accusamus impedit ut provident. Ipsam omnis ut sit voluptatem ab culpa neque. Saepe temporibus voluptas enim voluptatem neque ratione laudantium.', 'officiis', 32, NULL, '2010-11-25 13:45:50', '2019-07-27 09:30:11');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('22', '2', '212', 'Voluptates non rerum sequi dolores non. Dicta est et facilis tenetur repudiandae veritatis ratione. Quidem aut minus vitae.', 'id', 2980, NULL, '1978-10-05 10:39:46', '2003-07-15 20:25:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('23', '3', '214', 'Ipsa consequatur sint pariatur veniam corporis. Omnis sed nihil est cumque aut eius dignissimos. Amet consectetur nemo ut omnis eveniet. Voluptatibus et officiis doloremque expedita optio.', 'sequi', 8913243, NULL, '1984-07-13 13:34:35', '2015-10-17 21:52:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('24', '4', '216', 'Cupiditate quisquam qui explicabo praesentium occaecati vel. Expedita tempore ut voluptatibus explicabo deserunt dolor. Delectus debitis doloribus laborum.', 'animi', 1816321, NULL, '2000-03-06 06:36:44', '1972-03-02 21:46:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('25', '5', '218', 'Rerum architecto magnam dolorem provident. Maiores omnis praesentium beatae illum omnis aut. Non in dolorem omnis consequatur aut.', 'et', 913346, NULL, '1996-03-13 10:45:07', '1996-06-23 11:36:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('26', '6', '220', 'Assumenda libero at omnis velit eum. Qui rem voluptatibus sint voluptatem harum.', 'debitis', 26381, NULL, '1990-09-08 14:58:57', '1979-07-29 13:29:30');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('27', '7', '221', 'Quidem quisquam et ex et quis quia illo. Alias corporis hic quis sit labore architecto magni. Recusandae quo similique accusantium omnis accusamus non. Ut ea expedita rerum fuga dolores rerum deleniti mollitia.', 'alias', 4868, NULL, '1998-06-19 07:23:18', '2010-09-13 08:31:07');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('28', '8', '222', 'Libero dolorum molestiae itaque. Aut veritatis tenetur id alias tempore consequatur. Odit odio odit maiores.', 'cupiditate', 92643896, NULL, '1994-06-06 05:02:40', '1984-09-09 13:38:50');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('29', '9', '223', 'Mollitia et qui nesciunt aut accusamus. Qui beatae eum fuga rerum. Et quasi accusantium architecto quia possimus. Eos consequuntur eligendi aut et consectetur qui quia.', 'asperiores', 5, NULL, '2021-05-12 18:44:38', '1984-04-25 00:30:45');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('30', '10', '226', 'Fugit eum consequatur praesentium eum. Deserunt sed voluptatem dolorem sunt molestias ducimus. Perferendis quia maxime porro dolores maxime asperiores ducimus sed. Itaque ex velit id et nihil suscipit sed nemo.', 'quam', 96088567, NULL, '2011-09-15 06:56:45', '2009-01-03 05:04:18');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('31', '1', '227', 'Ut veritatis et dolorem expedita repudiandae. Fugiat sunt numquam qui. Necessitatibus sed dolores sapiente neque.', 'quos', 57, NULL, '1985-07-22 04:59:54', '1974-05-27 13:06:58');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('32', '2', '232', 'Repellat quas odit harum modi explicabo. Hic commodi itaque minima maiores.', 'modi', 967, NULL, '1986-01-10 22:46:58', '1985-03-07 22:26:06');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('33', '3', '234', 'Eaque corporis culpa omnis qui eius dolorem architecto. Deleniti voluptates accusantium deleniti quaerat nostrum. Dignissimos quam labore dolore aut.', 'ullam', 77529779, NULL, '1970-05-15 18:45:04', '2016-06-19 10:09:23');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('34', '4', '235', 'Nisi delectus fugiat aperiam autem. Ad officiis sint et esse sit velit et. Expedita non quisquam nostrum natus cum perspiciatis. Pariatur enim repellendus illum neque.', 'autem', 5, NULL, '1981-04-01 23:26:41', '2000-10-15 00:04:07');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('35', '5', '236', 'Quidem voluptas magnam voluptatem pariatur et esse sint. Deleniti autem veniam mollitia consequatur quia id soluta.', 'sed', 60, NULL, '2003-10-30 14:21:24', '2020-03-05 01:47:26');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('36', '6', '237', 'Odit aut nisi nobis molestiae aut quae et omnis. Totam iusto quasi animi repudiandae ut eum delectus et. Et repellat aut inventore fuga voluptatem ut aut fugiat. Laborum iusto nisi at iusto. Magni praesentium sunt harum odit.', 'iure', 46913296, NULL, '1972-09-16 19:54:10', '1990-09-08 02:08:31');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('37', '7', '239', 'Ad iste error voluptas eaque accusamus. Nihil porro sunt recusandae sit pariatur pariatur. Quisquam molestiae qui quia delectus voluptatem voluptatem ea. Quam in est commodi vel quisquam est.', 'cum', 0, NULL, '2006-04-17 14:19:50', '2008-09-18 22:18:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('38', '8', '240', 'Necessitatibus expedita earum nesciunt sit fugiat facilis unde. Neque qui et qui natus et voluptate consectetur. Quo ut maiores quis error quia non inventore non.', 'laudantium', 7536586, NULL, '2012-03-02 04:54:46', '1998-07-09 04:27:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('39', '9', '242', 'Dolorem nihil omnis qui quia. Ipsa est ab nesciunt aspernatur accusamus. Consequuntur doloremque odit corrupti voluptatum. Earum doloribus quis quos non. Totam laboriosam est illum sed voluptate nulla totam.', 'quo', 723567, NULL, '1994-11-23 14:58:05', '1973-11-24 09:29:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('40', '10', '243', 'Consectetur alias odit consequuntur velit non rem. Modi explicabo perferendis facilis et sunt quisquam. Doloremque et consectetur reprehenderit eum.', 'rerum', 27249, NULL, '2005-11-29 18:17:48', '2002-08-27 21:29:09');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('41', '1', '245', 'Fugit mollitia amet quo maiores. Laudantium est laborum at. Fugiat ut illo et vel libero iure.', 'quasi', 25676, NULL, '2006-06-25 05:31:59', '2015-08-08 01:31:51');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('42', '2', '246', 'Enim assumenda velit incidunt. Dolorem officia itaque deserunt rerum animi modi omnis. Exercitationem modi ab quos explicabo unde temporibus.', 'inventore', 49, NULL, '1991-08-10 11:21:06', '1998-02-28 15:34:00');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('43', '3', '247', 'Sit sit nesciunt inventore vitae illum placeat illo. Autem iusto voluptas repudiandae debitis. Saepe dolor dignissimos et maiores porro ipsa.', 'aliquid', 7308849, NULL, '1992-05-31 07:14:54', '1998-02-17 21:41:09');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('44', '4', '248', 'Quisquam quibusdam dignissimos natus aperiam aperiam saepe eius. Nobis soluta qui ducimus qui nemo quo. Recusandae nisi dolores non facilis.', 'possimus', 87, NULL, '1982-01-04 14:06:15', '2010-09-14 18:44:42');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('45', '5', '249', 'Non aut quibusdam velit vero nam. Tempora cumque aliquam tempora molestiae excepturi. Debitis voluptates suscipit quia.', 'non', 0, NULL, '2015-11-29 17:22:30', '1970-01-13 19:59:33');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('46', '6', '252', 'Aut ipsum nemo minus quibusdam voluptate nisi et. Quis dolores perferendis cupiditate rem aut veniam ipsa ipsa. Eveniet necessitatibus cum cumque sequi voluptatem saepe debitis.', 'nihil', 67501504, NULL, '1978-05-15 03:02:57', '1979-09-09 08:35:00');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('47', '7', '254', 'Autem porro eligendi et in reprehenderit sapiente optio. Quae saepe quis expedita minus temporibus maiores dicta. In impedit hic pariatur possimus. Qui est dolorem officia ut ducimus eos aperiam animi.', 'praesentium', 0, NULL, '2007-12-17 22:00:24', '2003-03-30 23:19:36');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('48', '8', '255', 'Dolores optio fugit soluta id et velit. Repudiandae molestias voluptatem ut et eius corporis. Quasi laboriosam similique quae odit et et.', 'qui', 15342024, NULL, '1999-07-19 09:03:16', '1990-07-03 17:18:17');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('49', '9', '257', 'Asperiores molestias repellat ad eos numquam cumque. Ad accusantium a voluptatem. Omnis eligendi dolor sit dolores praesentium.', 'magni', 340, NULL, '1976-10-30 19:27:06', '1975-05-13 15:04:18');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('50', '10', '261', 'Minima quod ut enim adipisci perspiciatis. Fugiat amet consequatur corporis alias. Reprehenderit id quaerat eius veritatis nihil ducimus saepe.', 'voluptatem', 585102953, NULL, '1971-06-19 19:48:21', '2018-06-06 03:28:00');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('51', '1', '263', 'Sed rerum aut sunt fuga aliquid. Nulla nesciunt sit sequi eligendi. Qui error autem consequatur dicta fugiat ratione mollitia rem.', 'commodi', 77, NULL, '1978-11-02 08:19:40', '1986-08-29 23:32:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('52', '2', '264', 'Enim unde laborum illum repudiandae ipsam. Libero at quo et facere nihil.', 'reprehenderit', 123, NULL, '2008-05-17 20:01:12', '1987-09-11 06:22:12');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('53', '3', '265', 'Nisi non rerum iusto et aut. Nesciunt maiores accusantium atque cum dolorem. Consequatur earum sed earum impedit dicta odio. Non rem impedit minus aliquam.', 'est', 600444399, NULL, '2018-10-24 14:56:04', '1980-09-06 19:54:41');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('54', '4', '266', 'In voluptatem fugiat dolore voluptates ducimus. Natus sed laudantium doloribus quidem id quibusdam repudiandae vel. Eveniet in aperiam et dicta praesentium ad. Eveniet ut dolor consequatur repudiandae nostrum eos.', 'illum', 6692, NULL, '2000-03-13 18:37:31', '2004-04-28 01:51:28');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('55', '5', '267', 'Totam eum doloribus libero sint qui. Est soluta est consequatur earum eveniet impedit. Suscipit culpa cupiditate ut vitae.', 'ut', 4063, NULL, '1998-05-17 03:16:18', '1974-06-22 04:29:10');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('56', '6', '268', 'Non eum ut accusantium. Harum numquam et cumque odio sed qui. Aut atque accusantium commodi voluptatum rerum. Tenetur ipsum in distinctio.', 'dolores', 497047, NULL, '2017-05-23 16:20:25', '2000-03-27 15:56:27');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('57', '7', '271', 'Autem autem praesentium omnis voluptatem iusto. Id odit ut sunt unde error pariatur. Repellendus enim ipsa aut et illum ratione ut.', 'iusto', 87919, NULL, '1993-02-27 03:23:04', '1974-12-23 20:07:54');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('58', '8', '272', 'Quo possimus rerum hic sint est ducimus non. Qui asperiores quibusdam assumenda omnis est. At quis aut fugit facere debitis pariatur. Omnis alias expedita quas aliquam consequatur quas aliquam dignissimos.', 'quia', 614670, NULL, '1977-03-20 16:15:34', '1981-03-26 04:54:47');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('59', '9', '273', 'Explicabo tenetur ducimus similique et voluptatibus aut. Quia reiciendis et sit aliquid voluptates. Sint esse deserunt sapiente harum numquam blanditiis id. Recusandae dignissimos sed ea omnis et cupiditate.', 'et', 83294176, NULL, '1976-06-12 19:01:07', '1990-01-02 00:32:12');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('60', '10', '274', 'Quasi quas voluptate impedit est. Dolor eos impedit voluptatibus. Eum nihil corrupti natus molestias recusandae sed. Repellat quas deleniti doloremque sit. Culpa aut harum consequuntur eveniet voluptas accusantium natus.', 'saepe', 7746778, NULL, '1980-12-09 08:57:04', '1978-04-28 16:02:40');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('61', '1', '276', 'Accusamus laudantium molestiae est optio. Esse nulla laborum et vel dolor. Voluptatem et qui sit est iure deserunt. Cumque vel quia ut id temporibus.', 'numquam', 577, NULL, '2003-11-21 18:26:17', '1974-05-16 09:54:03');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('62', '2', '277', 'Illo voluptates vero odio. Autem quo eos dolorem ea earum.', 'id', 2, NULL, '1988-05-09 08:46:29', '1977-12-30 02:07:07');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('63', '3', '278', 'Incidunt et rerum eum laborum sit. Cum quae voluptate itaque autem voluptas id. Voluptatem est at aliquid. Enim omnis ut sapiente et. Alias pariatur veniam amet rerum.', 'nihil', 3337006, NULL, '2021-07-14 11:22:14', '1997-01-24 22:28:45');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('64', '4', '279', 'Ipsum ab est rerum facilis. Accusamus natus quod consequuntur consequuntur. Odio molestias rem distinctio numquam nihil repellendus.', 'rerum', 4977185, NULL, '1996-09-10 13:42:39', '2021-03-15 12:36:47');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('65', '5', '282', 'Modi tempore quae dignissimos nam. Dignissimos sunt ab dolorum. Similique dolorem quia culpa molestiae perferendis veniam et. Aliquid numquam recusandae odit eveniet sint ut. Aperiam deserunt ut occaecati vel ducimus.', 'quas', 63, NULL, '1999-08-16 07:48:16', '1990-12-10 22:23:14');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('66', '6', '283', 'Fugit blanditiis molestias error architecto quisquam. Delectus perspiciatis voluptas provident cum ratione voluptatem quo est. Nam non ut quia non.', 'mollitia', 78674, NULL, '1996-12-09 15:29:44', '2020-01-19 22:11:51');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('67', '7', '286', 'Delectus dicta vel dolorum quae. Eum laudantium repellendus quos ipsa officiis. Doloribus quasi veritatis rerum aperiam fuga. Molestiae porro in sed natus laboriosam.', 'itaque', 6834064, NULL, '1996-12-07 20:25:47', '2020-08-31 00:45:53');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('68', '8', '288', 'Omnis corporis rerum vero esse est omnis repellat. Amet veritatis eum sint quas a saepe. Qui in non vel. Delectus eius est dolorem delectus velit labore.', 'itaque', 7455879, NULL, '1979-07-10 09:52:06', '2015-02-04 16:04:55');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('69', '9', '290', 'Illum eos autem maiores et. Expedita tempore accusamus corporis illum. Voluptas repellendus reiciendis accusamus et sint quasi a.', 'est', 20903409, NULL, '2011-01-08 17:54:22', '1975-04-15 00:52:18');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('70', '10', '291', 'Dolor consequatur ex illum illo. In omnis vel qui officia dolorem nobis. Vitae atque harum occaecati accusamus quo nesciunt est. Exercitationem sed deleniti quia ut ratione in quia. Voluptas sint at blanditiis occaecati necessitatibus ut nihil.', 'nisi', 58, NULL, '2016-11-16 12:59:50', '1990-10-12 01:29:12');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('71', '1', '294', 'Quia in itaque qui optio. Itaque error voluptates magnam nesciunt itaque aliquam animi. Autem ut sed assumenda fugit.', 'iure', 99052, NULL, '2016-04-17 12:31:44', '2016-02-22 19:00:42');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('72', '2', '297', 'Expedita porro quos aut. Natus quam nihil ab qui et non ipsum. Quasi accusamus rem magni praesentium quidem. Quia fuga eum et optio deleniti.', 'ut', 450, NULL, '2011-03-05 06:38:47', '1999-10-24 18:28:02');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('73', '3', '299', 'Repudiandae adipisci totam qui dolor aut quia asperiores. Est et tempore culpa.', 'nemo', 47, NULL, '2004-05-28 02:05:10', '2006-09-14 23:30:18');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('74', '4', '301', 'Impedit culpa dolore quam sit quidem. Labore dignissimos soluta vero distinctio doloremque unde suscipit.', 'magnam', 616446147, NULL, '1978-09-30 13:08:37', '2010-05-09 01:58:57');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('75', '5', '302', 'Voluptatem ipsam placeat cumque non. Tempore dicta adipisci dolores occaecati doloribus et. Nostrum quo dicta sed odit praesentium qui. Delectus placeat est asperiores est at officiis.', 'sint', 66941573, NULL, '1976-04-02 15:30:23', '1978-04-22 08:20:17');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('76', '6', '303', 'Autem nulla veniam adipisci vel dolor ratione non. Sunt quibusdam et expedita et. Quidem totam pariatur occaecati voluptatem sint tenetur quaerat fugiat.', 'totam', 72, NULL, '1978-07-14 11:18:25', '2013-09-07 03:46:05');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('77', '7', '305', 'Aut odio enim quia rerum voluptas dolores. A eveniet porro soluta soluta aperiam non esse.', 'aut', 9, NULL, '1973-02-22 10:46:35', '1995-10-05 18:25:40');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('78', '8', '306', 'Dolor est quia nulla veniam at. Sunt nihil molestias eum veritatis et. Aperiam cupiditate voluptas accusantium et ab sequi.', 'magnam', 39976832, NULL, '1970-09-02 11:40:00', '2002-02-13 04:58:17');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('79', '9', '308', 'Aut non excepturi sapiente aut. Velit et illum eius placeat maiores quibusdam. Temporibus voluptatem quasi et laudantium velit doloribus.', 'enim', 252941937, NULL, '2005-06-16 19:12:38', '1981-08-10 15:04:43');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('80', '10', '310', 'Quod repellat dicta fuga omnis perferendis. Aperiam accusantium ullam sint quas ut. Velit similique vero consectetur voluptatem temporibus reprehenderit. Incidunt illo in illo dolores.', 'praesentium', 226289, NULL, '1989-04-28 21:11:46', '1997-03-09 22:51:47');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('81', '1', '312', 'Quia iusto odit ad similique amet dolorem voluptatem magnam. Pariatur debitis molestias in assumenda enim et. Dolorem id eos consequuntur et ex aperiam. Enim temporibus rerum dolor quasi rerum repudiandae sed.', 'maiores', 845, NULL, '2008-10-09 13:13:07', '1990-02-21 02:46:39');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('82', '2', '313', 'Deleniti inventore qui et minus. Excepturi sapiente distinctio quod ex at laudantium. Perferendis repellendus repellat itaque quis sit. Iure rerum id exercitationem sunt velit. Iure possimus sit non fugit quod placeat corporis.', 'vel', 203548204, NULL, '1982-03-01 10:37:31', '2012-06-05 23:55:35');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('83', '3', '315', 'Accusantium adipisci aut dicta laudantium eveniet. Est eligendi blanditiis dolorem est quo reiciendis consequatur rerum. Consectetur ipsa et architecto. Molestiae qui velit iusto dolorem culpa aut molestias.', 'deleniti', 6303, NULL, '1987-02-03 02:58:34', '1998-10-27 22:22:42');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('84', '4', '316', 'Consequuntur enim dolore cupiditate blanditiis numquam. Ut voluptas expedita voluptate vitae neque quo est.', 'dignissimos', 0, NULL, '1979-09-19 01:30:35', '1980-11-26 04:11:54');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('85', '5', '317', 'Aliquam sunt est velit sunt. Ipsa laborum commodi numquam voluptatem. Minima qui sit animi rerum ratione dolorem.', 'ex', 892145345, NULL, '1981-03-07 06:46:08', '2011-10-25 23:09:07');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('86', '6', '322', 'Et mollitia ex facere quis. Dolore sed dolor asperiores deserunt corporis. Vero necessitatibus eum consequatur sunt id. A at dicta in iure. Ut occaecati dolor est molestiae voluptatem deleniti non.', 'ut', 77789, NULL, '1987-12-08 11:05:22', '1979-02-02 11:31:53');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('87', '7', '323', 'Temporibus quae ratione distinctio cupiditate. Adipisci cum quaerat tempore et consequatur eveniet. Maxime aut rerum ducimus qui voluptatem in nemo.', 'incidunt', 0, NULL, '2017-10-02 13:05:00', '2010-12-12 15:42:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('88', '8', '328', 'Quia necessitatibus cupiditate ut quis adipisci eum voluptatem est. Eos sed nobis omnis illo voluptatem ad explicabo. Ut voluptatem sed et et a. Quia sunt aut reiciendis pariatur ad quia explicabo.', 'dolore', 3476, NULL, '2002-05-09 00:19:15', '2010-11-16 13:32:19');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('89', '9', '330', 'Ullam sit eveniet commodi et omnis. Asperiores est earum aut veniam optio. Deleniti quod non facere ex distinctio rem atque neque.', 'ex', 40, NULL, '1997-09-27 00:35:38', '1989-04-18 03:39:10');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('90', '10', '331', 'Inventore quas minus recusandae. Enim pariatur unde tempore dignissimos. Provident repellat reprehenderit tenetur mollitia. Non sed corporis sequi tempore iste ipsa.', 'soluta', 80865, NULL, '1982-01-03 03:17:42', '1970-04-12 18:41:34');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('91', '1', '332', 'Quam sit aut vero dolor officia tempora excepturi eum. Reiciendis qui voluptatem veniam. A consectetur nemo id repellat laborum nisi id. Id mollitia nihil velit corporis aliquid consequatur.', 'doloribus', 4, NULL, '2004-01-22 07:22:21', '1975-01-17 13:50:31');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('92', '2', '335', 'Eum harum dignissimos eligendi beatae cumque aut in. Incidunt repellat sint inventore animi id fugiat quia. Expedita similique dolores aperiam ea.', 'sit', 31389743, NULL, '1972-07-10 13:26:51', '1977-04-26 18:25:13');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('93', '3', '339', 'Natus qui iure ut perspiciatis. Ullam nisi ut iusto.', 'doloribus', 60364101, NULL, '2019-06-17 15:34:35', '1992-04-29 23:00:00');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('94', '4', '341', 'Consequuntur voluptatibus consequuntur cupiditate blanditiis fuga harum animi. Ullam dolorem animi sunt qui aut. Omnis iste ut vel et reprehenderit. Eos laboriosam id repudiandae sit sint itaque odio.', 'provident', 6342194, NULL, '1990-07-11 19:04:15', '1988-01-01 22:01:50');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('95', '5', '342', 'Ut nemo similique vero veniam. Quis ipsam ullam distinctio voluptate sit.', 'temporibus', 28052, NULL, '1991-11-17 17:21:46', '2020-11-22 04:06:07');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('96', '6', '343', 'Omnis consequatur quos quos blanditiis. Ea modi nobis consectetur quaerat sit sit dolorem. Recusandae necessitatibus ipsa officiis aut ex. Quis dolorem consequatur enim laborum fugit.', 'ratione', 970, NULL, '1988-12-04 10:45:24', '2006-08-26 05:50:25');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('97', '7', '344', 'Sit non ut omnis dolorem temporibus ut error tenetur. Enim inventore eum et autem beatae non ullam. Voluptas sed beatae consequatur soluta pariatur inventore. Rerum eos animi aperiam id quia voluptate minima.', 'nesciunt', 635, NULL, '2002-03-24 08:55:00', '1971-10-28 18:46:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('98', '8', '345', 'Aut voluptatem voluptate mollitia veniam quisquam aliquam. Rerum molestiae natus voluptatem enim neque facere dolorem quo. Rerum laborum officiis molestiae eligendi et ea aspernatur. Placeat sit aperiam eum vitae.', 'ut', 0, NULL, '1971-07-01 09:24:59', '1981-09-30 12:40:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('99', '9', '346', 'Tempora harum provident omnis laboriosam. Animi quia labore doloremque necessitatibus eum. Rem praesentium illum quo facilis autem accusantium odit. Id aspernatur id nihil et sed assumenda consequatur.', 'ut', 8, NULL, '2011-05-03 08:35:17', '1980-12-17 23:56:26');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('100', '10', '350', 'Sed et voluptates rem dolorum nihil. Sunt aliquid qui et odit possimus quas et. Veritatis libero et in sit iure et omnis.', 'consequatur', 9661, NULL, '2015-04-17 07:31:37', '1973-07-21 23:37:08');


